# 温泉插件 for Minecraft
# 版本：1.0
# 
# 本插件中 所有 的 & 彩色代码都可以使用 & 代替
Enable: true
debug: false
# 启用本插件（false禁用）
TooMuch: '&4[温泉] 警告！你已经过度泡温泉了！快离开温泉！'
Healing: '&2[温泉] 你正在被治疗！'
Poison: '&4[温泉] 你因泡温泉时间过长，导致脱水中毒！'
Explosion: '&2[温泉] &4玩家 %player% 因泡温泉时间太长而身体爆裂而死！'